ALTER TABLE agent ALTER COLUMN raw_jwt DROP NOT NULL;
ALTER TABLE agent ALTER COLUMN label DROP NOT NULL;


ALTER TABLE connection ALTER COLUMN approved DROP NOT NULL;
ALTER TABLE connection ALTER COLUMN approved SET DEFAULT NULL;

ALTER TABLE connection ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE connection ALTER COLUMN archived SET DEFAULT NULL;
