ALTER TABLE agent ALTER COLUMN raw_jwt DROP NOT NULL;
ALTER TABLE agent ALTER COLUMN label DROP NOT NULL;


ALTER TABLE connection ALTER COLUMN approved DROP NOT NULL;
ALTER TABLE connection ALTER COLUMN approved SET DEFAULT NULL;

ALTER TABLE connection ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE connection ALTER COLUMN archived SET DEFAULT NULL;


ALTER TABLE credential ALTER COLUMN approved DROP NOT NULL;
ALTER TABLE credential ALTER COLUMN approved SET DEFAULT NULL;

ALTER TABLE credential ALTER COLUMN issued DROP NOT NULL;
ALTER TABLE credential ALTER COLUMN issued SET DEFAULT NULL;

ALTER TABLE credential ALTER COLUMN failed DROP NOT NULL;
ALTER TABLE credential ALTER COLUMN failed SET DEFAULT NULL;

ALTER TABLE credential ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE credential ALTER COLUMN archived SET DEFAULT NULL;



ALTER TABLE proof ALTER COLUMN provable DROP NOT NULL;
ALTER TABLE proof ALTER COLUMN provable SET DEFAULT NULL;

ALTER TABLE proof ALTER COLUMN approved DROP NOT NULL;
ALTER TABLE proof ALTER COLUMN approved SET DEFAULT NULL;

ALTER TABLE proof ALTER COLUMN verified DROP NOT NULL;
ALTER TABLE proof ALTER COLUMN verified SET DEFAULT NULL;

ALTER TABLE proof ALTER COLUMN failed DROP NOT NULL;
ALTER TABLE proof ALTER COLUMN failed SET DEFAULT NULL;

ALTER TABLE proof ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE proof ALTER COLUMN archived SET DEFAULT NULL;


ALTER TABLE message ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE message ALTER COLUMN archived SET DEFAULT NULL;
