linters-settings:
  dupl:
    threshold: 225
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "ioutil is deprecated starting with Go 1.16"
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    #- containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    #- exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    #- gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    #- godot
    #- godox
    #- goerr113
    - gofmt
    #- gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    #- ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    #- nestif
    - nilerr
    - nilnil
    #- nlreturn
    - noctx
    - nolintlint
    #- nonamedreturns
    - nosprintfhostport
    #- paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    #- rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    #- testpackage
    #- thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    #- varnamelen
    - wastedassign
    - whitespace
    #    - wrapcheck
    #    - wsl
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - gochecknoglobals
    - path: db/store/pg/pg.go
      linters:
        - gocritic
      text: "ptrToRefParam:"
    - path: db/store/pg/
      linters:
        - dupl
    - path: db/store/mock
      linters:
        - dupl
    - path: resolver/schema.resolvers.go
      linters:
        - gocritic
        - lll
    - path: resolver/test/doc_test.go
      linters:
        - golint
        - staticcheck
    - path: agency/findy/status_test.go
      linters:
        - funlen
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
run:
service:
  golangci-lint-version: 1.54.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
