package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/findy-network/findy-agent-vault/graph/generated"
	"github.com/findy-network/findy-agent-vault/graph/model"
)

// Connection is the resolver for the connection field.
func (r *basicMessageResolver) Connection(ctx context.Context, obj *model.BasicMessage) (*model.Pairwise, error) {
	return r.resolvers.message.Connection(ctx, obj)
}

// TotalCount is the resolver for the totalCount field.
func (r *basicMessageConnectionResolver) TotalCount(ctx context.Context, obj *model.BasicMessageConnection) (int, error) {
	return r.resolvers.messageConnection.TotalCount(ctx, obj)
}

// Connection is the resolver for the connection field.
func (r *credentialResolver) Connection(ctx context.Context, obj *model.Credential) (*model.Pairwise, error) {
	return r.resolvers.credential.Connection(ctx, obj)
}

// TotalCount is the resolver for the totalCount field.
func (r *credentialConnectionResolver) TotalCount(ctx context.Context, obj *model.CredentialConnection) (int, error) {
	return r.resolvers.credentialConnection.TotalCount(ctx, obj)
}

// Job is the resolver for the job field.
func (r *eventResolver) Job(ctx context.Context, obj *model.Event) (*model.JobEdge, error) {
	return r.resolvers.event.Job(ctx, obj)
}

// Connection is the resolver for the connection field.
func (r *eventResolver) Connection(ctx context.Context, obj *model.Event) (*model.Pairwise, error) {
	return r.resolvers.event.Connection(ctx, obj)
}

// TotalCount is the resolver for the totalCount field.
func (r *eventConnectionResolver) TotalCount(ctx context.Context, obj *model.EventConnection) (int, error) {
	return r.resolvers.eventConnection.TotalCount(ctx, obj)
}

// Output is the resolver for the output field.
func (r *jobResolver) Output(ctx context.Context, obj *model.Job) (*model.JobOutput, error) {
	return r.resolvers.job.Output(ctx, obj)
}

// TotalCount is the resolver for the totalCount field.
func (r *jobConnectionResolver) TotalCount(ctx context.Context, obj *model.JobConnection) (int, error) {
	return r.resolvers.jobConnection.TotalCount(ctx, obj)
}

// MarkEventRead is the resolver for the markEventRead field.
func (r *mutationResolver) MarkEventRead(ctx context.Context, input model.MarkReadInput) (*model.Event, error) {
	return r.resolvers.mutation.MarkEventRead(ctx, input)
}

// Invite is the resolver for the invite field.
func (r *mutationResolver) Invite(ctx context.Context) (*model.InvitationResponse, error) {
	return r.resolvers.mutation.Invite(ctx)
}

// Connect is the resolver for the connect field.
func (r *mutationResolver) Connect(ctx context.Context, input model.ConnectInput) (*model.Response, error) {
	return r.resolvers.mutation.Connect(ctx, input)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.MessageInput) (*model.Response, error) {
	return r.resolvers.mutation.SendMessage(ctx, input)
}

// Resume is the resolver for the resume field.
func (r *mutationResolver) Resume(ctx context.Context, input model.ResumeJobInput) (*model.Response, error) {
	return r.resolvers.mutation.Resume(ctx, input)
}

// Messages is the resolver for the messages field.
func (r *pairwiseResolver) Messages(ctx context.Context, obj *model.Pairwise, after *string, before *string, first *int, last *int) (*model.BasicMessageConnection, error) {
	return r.resolvers.pairwise.Messages(ctx, obj, after, before, first, last)
}

// Credentials is the resolver for the credentials field.
func (r *pairwiseResolver) Credentials(ctx context.Context, obj *model.Pairwise, after *string, before *string, first *int, last *int) (*model.CredentialConnection, error) {
	return r.resolvers.pairwise.Credentials(ctx, obj, after, before, first, last)
}

// Proofs is the resolver for the proofs field.
func (r *pairwiseResolver) Proofs(ctx context.Context, obj *model.Pairwise, after *string, before *string, first *int, last *int) (*model.ProofConnection, error) {
	return r.resolvers.pairwise.Proofs(ctx, obj, after, before, first, last)
}

// Jobs is the resolver for the jobs field.
func (r *pairwiseResolver) Jobs(ctx context.Context, obj *model.Pairwise, after *string, before *string, first *int, last *int, completed *bool) (*model.JobConnection, error) {
	return r.resolvers.pairwise.Jobs(ctx, obj, after, before, first, last, completed)
}

// Events is the resolver for the events field.
func (r *pairwiseResolver) Events(ctx context.Context, obj *model.Pairwise, after *string, before *string, first *int, last *int) (*model.EventConnection, error) {
	return r.resolvers.pairwise.Events(ctx, obj, after, before, first, last)
}

// TotalCount is the resolver for the totalCount field.
func (r *pairwiseConnectionResolver) TotalCount(ctx context.Context, obj *model.PairwiseConnection) (int, error) {
	return r.resolvers.pairwiseConnection.TotalCount(ctx, obj)
}

// Provable is the resolver for the provable field.
func (r *proofResolver) Provable(ctx context.Context, obj *model.Proof) (*model.Provable, error) {
	return r.resolvers.proof.Provable(ctx, obj)
}

// Connection is the resolver for the connection field.
func (r *proofResolver) Connection(ctx context.Context, obj *model.Proof) (*model.Pairwise, error) {
	return r.resolvers.proof.Connection(ctx, obj)
}

// TotalCount is the resolver for the totalCount field.
func (r *proofConnectionResolver) TotalCount(ctx context.Context, obj *model.ProofConnection) (int, error) {
	return r.resolvers.proofConnection.TotalCount(ctx, obj)
}

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context, after *string, before *string, first *int, last *int) (*model.PairwiseConnection, error) {
	return r.resolvers.query.Connections(ctx, after, before, first, last)
}

// Connection is the resolver for the connection field.
func (r *queryResolver) Connection(ctx context.Context, id string) (*model.Pairwise, error) {
	return r.resolvers.query.Connection(ctx, id)
}

// Message is the resolver for the message field.
func (r *queryResolver) Message(ctx context.Context, id string) (*model.BasicMessage, error) {
	return r.resolvers.query.Message(ctx, id)
}

// Credential is the resolver for the credential field.
func (r *queryResolver) Credential(ctx context.Context, id string) (*model.Credential, error) {
	return r.resolvers.query.Credential(ctx, id)
}

// Credentials is the resolver for the credentials field.
func (r *queryResolver) Credentials(ctx context.Context, after *string, before *string, first *int, last *int) (*model.CredentialConnection, error) {
	return r.resolvers.query.Credentials(ctx, after, before, first, last)
}

// Proof is the resolver for the proof field.
func (r *queryResolver) Proof(ctx context.Context, id string) (*model.Proof, error) {
	return r.resolvers.query.Proof(ctx, id)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, after *string, before *string, first *int, last *int) (*model.EventConnection, error) {
	return r.resolvers.query.Events(ctx, after, before, first, last)
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	return r.resolvers.query.Event(ctx, id)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, after *string, before *string, first *int, last *int, completed *bool) (*model.JobConnection, error) {
	return r.resolvers.query.Jobs(ctx, after, before, first, last, completed)
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.Job, error) {
	return r.resolvers.query.Job(ctx, id)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	return r.resolvers.query.User(ctx)
}

// Endpoint is the resolver for the endpoint field.
func (r *queryResolver) Endpoint(ctx context.Context, payload string) (*model.InvitationResponse, error) {
	return r.resolvers.query.Endpoint(ctx, payload)
}

// EventAdded is the resolver for the eventAdded field.
func (r *subscriptionResolver) EventAdded(ctx context.Context) (<-chan *model.EventEdge, error) {
	return r.updater.EventAdded(ctx)
}

// BasicMessage returns generated.BasicMessageResolver implementation.
func (r *Resolver) BasicMessage() generated.BasicMessageResolver { return &basicMessageResolver{r} }

// BasicMessageConnection returns generated.BasicMessageConnectionResolver implementation.
func (r *Resolver) BasicMessageConnection() generated.BasicMessageConnectionResolver {
	return &basicMessageConnectionResolver{r}
}

// Credential returns generated.CredentialResolver implementation.
func (r *Resolver) Credential() generated.CredentialResolver { return &credentialResolver{r} }

// CredentialConnection returns generated.CredentialConnectionResolver implementation.
func (r *Resolver) CredentialConnection() generated.CredentialConnectionResolver {
	return &credentialConnectionResolver{r}
}

// Event returns generated.EventResolver implementation.
func (r *Resolver) Event() generated.EventResolver { return &eventResolver{r} }

// EventConnection returns generated.EventConnectionResolver implementation.
func (r *Resolver) EventConnection() generated.EventConnectionResolver {
	return &eventConnectionResolver{r}
}

// Job returns generated.JobResolver implementation.
func (r *Resolver) Job() generated.JobResolver { return &jobResolver{r} }

// JobConnection returns generated.JobConnectionResolver implementation.
func (r *Resolver) JobConnection() generated.JobConnectionResolver { return &jobConnectionResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Pairwise returns generated.PairwiseResolver implementation.
func (r *Resolver) Pairwise() generated.PairwiseResolver { return &pairwiseResolver{r} }

// PairwiseConnection returns generated.PairwiseConnectionResolver implementation.
func (r *Resolver) PairwiseConnection() generated.PairwiseConnectionResolver {
	return &pairwiseConnectionResolver{r}
}

// Proof returns generated.ProofResolver implementation.
func (r *Resolver) Proof() generated.ProofResolver { return &proofResolver{r} }

// ProofConnection returns generated.ProofConnectionResolver implementation.
func (r *Resolver) ProofConnection() generated.ProofConnectionResolver {
	return &proofConnectionResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type basicMessageResolver struct{ *Resolver }
type basicMessageConnectionResolver struct{ *Resolver }
type credentialResolver struct{ *Resolver }
type credentialConnectionResolver struct{ *Resolver }
type eventResolver struct{ *Resolver }
type eventConnectionResolver struct{ *Resolver }
type jobResolver struct{ *Resolver }
type jobConnectionResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type pairwiseResolver struct{ *Resolver }
type pairwiseConnectionResolver struct{ *Resolver }
type proofResolver struct{ *Resolver }
type proofConnectionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
