name: golangci-lint
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use token
        run: git config --global url."https://"${{ secrets.https_prefix }}"github.com/".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
