name: release
on:  
  push:
    tags:
      - '*'
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      HTTPS_PREFIX: ${{ secrets.https_prefix }}
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: checkout
        uses: actions/checkout@v2
      - name: use token
        run: git config --global url."https://"${{ secrets.https_prefix }}"github.com/".insteadOf "git@github.com:"
      - name: clone deps
        run: cd demo && make clone
      - name: build cli
        run: cd demo && make build_cli
      - name: test
        run: cd demo && make test TIMEOUT=5
  merge:
    needs: e2e
    runs-on: ubuntu-latest
    env:
      HTTPS_PREFIX: ${{ secrets.https_prefix }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        run: git checkout master && git merge dev && git push origin master