name: release
on:
  push:
    tags:
      - "*"
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      HTTPS_PREFIX: ${{ secrets.https_prefix }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use token
        run: git config --global url."https://"${{ secrets.https_prefix }}"github.com/".insteadOf "git@github.com:"
  # TODO: refactor and use new cli
  #      - name: clone deps
  #        run: cd demo && make clone
  #      - name: build cli
  #        run: cd demo && make build_cli
  #      - name: test
  #        run: cd demo && make test TIMEOUT=5
  merge:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          git config --global user.name "findy-agent-vault"
          git config --global user.email "findy-agent-vault"
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
